/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dangnhap;

import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Administrator
 */
public class BXH extends javax.swing.JFrame {

    /**
     * Creates new form BXH
     */
    public BXH() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtDiem = new javax.swing.JTextField();
        txtDoibong = new javax.swing.JTextField();
        txtStt = new javax.swing.JTextField();
        txtThang = new javax.swing.JTextField();
        txtThua = new javax.swing.JTextField();
        txtBanthua = new javax.swing.JTextField();
        txtHoa = new javax.swing.JTextField();
        txtBanthang = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        btnThem = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBXH = new javax.swing.JTable();
        lblError = new javax.swing.JLabel();
        txtSotran = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel1.setText("Điểm");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 280, -1, 20));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel2.setText("STT");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, 60, 20));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel3.setText("Số trận");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, -1, 20));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel4.setText("Thắng ");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 120, -1, 20));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel5.setText("Thua");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, -1, 20));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel6.setText("Hoà");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 160, -1, 20));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel7.setText("Bàn thắng");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, -1, 20));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel8.setText("Bàn thua");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 240, -1, 20));

        txtDiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDiemActionPerformed(evt);
            }
        });
        jPanel1.add(txtDiem, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 280, 90, -1));

        txtDoibong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDoibongActionPerformed(evt);
            }
        });
        jPanel1.add(txtDoibong, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, 170, -1));

        txtStt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSttActionPerformed(evt);
            }
        });
        jPanel1.add(txtStt, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, 50, -1));

        txtThang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtThangActionPerformed(evt);
            }
        });
        jPanel1.add(txtThang, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 120, 60, -1));

        txtThua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtThuaActionPerformed(evt);
            }
        });
        jPanel1.add(txtThua, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 160, 50, -1));

        txtBanthua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBanthuaActionPerformed(evt);
            }
        });
        jPanel1.add(txtBanthua, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 240, 170, -1));

        txtHoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHoaActionPerformed(evt);
            }
        });
        jPanel1.add(txtHoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 160, 60, -1));

        txtBanthang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBanthangActionPerformed(evt);
            }
        });
        jPanel1.add(txtBanthang, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 200, 170, -1));

        jButton1.setBackground(new java.awt.Color(153, 153, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Quay lại");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 480, 100, 30));

        btnThem.setText("Thêm ");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });
        jPanel1.add(btnThem, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 340, 80, 30));

        btnXoa.setText("Xoá ");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });
        jPanel1.add(btnXoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 340, 70, 30));

        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });
        jPanel1.add(btnSua, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 340, 70, 30));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(204, 204, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 51, 51));
        jLabel9.setText(" Bảng Xếp Hạng Các Đội Bóng");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, 290, 20));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 50));

        tblBXH.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "STT", "Đội Bóng", "Số Trận", "Thắng", "Thua", "Hoà", "Bàn thắng", "Bàn thua", "Điểm"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblBXH);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 610, 170));
        jPanel2.add(lblError, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 290, 410, 20));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 20, -1, 220));

        txtSotran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSotranActionPerformed(evt);
            }
        });
        jPanel1.add(txtSotran, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, 50, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel10.setText("Đội bóng");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, 60, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1148, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 535, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtDiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDiemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDiemActionPerformed

    private void txtDoibongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDoibongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDoibongActionPerformed

    private void txtSttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSttActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSttActionPerformed

    private void txtThangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtThangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtThangActionPerformed

    private void txtThuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtThuaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtThuaActionPerformed

    private void txtBanthuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBanthuaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBanthuaActionPerformed

    private void txtHoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHoaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHoaActionPerformed

    private void txtBanthangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBanthangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBanthangActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
setVisible(false);
new dangnhap().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        lblError.setText("");
        DefaultTableModel model =(DefaultTableModel) tblBXH.getModel();
        if (!txtDoibong.getText().trim().equals("")) {
            model.addRow(new Object[]{txtStt.getText(),txtDoibong.getText(), 
            txtSotran.getText(),txtThang.getText(),txtThua.getText(),txtHoa.getText(),
            txtBanthang.getText(),txtBanthua.getText(),txtDiem.getText()});
        } else {
            lblError.setText("Không được bỏ trống các trường");
        }
    }//GEN-LAST:event_btnThemActionPerformed

    private void txtSotranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSotranActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_txtSotranActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
                DefaultTableModel model = (DefaultTableModel) tblBXH.getModel();
        if (tblBXH.getSelectedRow()==-1) {
            if (tblBXH.getRowCount()==0) {
                lblError.setText("Trống");
            }
            else{
                lblError.setText("Bạn cần chọn tên Đội bóng");
            }
        }
        else{
            model.removeRow(tblBXH.getSelectedRow());
        }
        
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
                if (tblBXH.getSelectedRow()==-1) {
            if (tblBXH.getRowCount()==0) {
                lblError.setText("Trống");
            }
            else{
                lblError.setText("Bạn cần Phải điền đầy đủ thông tin");
            }
        }
        else{
            DefaultTableModel model = (DefaultTableModel) tblBXH.getModel();
            model.setValueAt(txtStt.getText(), tblBXH.getSelectedRow(), 0);
            model.setValueAt(txtDoibong.getText(),tblBXH.getSelectedRow(), 1);
            model.setValueAt(txtSotran.getText(), tblBXH.getSelectedRow(), 2);
            model.setValueAt(txtThang.getText(), tblBXH.getSelectedRow(), 3);
            model.setValueAt(txtThua.getText(), tblBXH.getSelectedRow(), 4);
            model.setValueAt(txtHoa.getText(), tblBXH.getSelectedRow(), 5);
            model.setValueAt(txtBanthang.getText(), tblBXH.getSelectedRow(), 6);
            model.setValueAt(txtBanthua.getText(), tblBXH.getSelectedRow(), 7);
            model.setValueAt(txtDiem.getText(), tblBXH.getSelectedRow(), 8);
        }
    }//GEN-LAST:event_btnSuaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BXH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BXH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BXH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BXH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BXH().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblError;
    private javax.swing.JTable tblBXH;
    private javax.swing.JTextField txtBanthang;
    private javax.swing.JTextField txtBanthua;
    private javax.swing.JTextField txtDiem;
    private javax.swing.JTextField txtDoibong;
    private javax.swing.JTextField txtHoa;
    private javax.swing.JTextField txtSotran;
    private javax.swing.JTextField txtStt;
    private javax.swing.JTextField txtThang;
    private javax.swing.JTextField txtThua;
    // End of variables declaration//GEN-END:variables
}
