/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dangnhap;

import javax.swing.JOptionPane;

/**
 *
 * @author Administrator
 */
public class dn extends javax.swing.JFrame {

    /**
     * Creates new form dn
     */
    public dn() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        vddangnhap = new javax.swing.JButton();
        vddangki = new javax.swing.JButton();
        btnQuenMatKhau = new javax.swing.JButton();
        jCheckBox1 = new javax.swing.JCheckBox();
        txtMatkhau = new javax.swing.JPasswordField();
        txtDangnhap = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quảnlígiảibóngđávkucup");

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(204, 255, 51));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, 60));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel1.setText(" Tài khoản");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 70, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel2.setText("Mật khẩu");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 80, -1));

        vddangnhap.setBackground(new java.awt.Color(153, 153, 255));
        vddangnhap.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        vddangnhap.setText("Đăng nhập");
        vddangnhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vddangnhapActionPerformed(evt);
            }
        });
        jPanel1.add(vddangnhap, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, 140, -1));

        vddangki.setBackground(new java.awt.Color(153, 153, 255));
        vddangki.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        vddangki.setText("Đăng kí");
        vddangki.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vddangkiActionPerformed(evt);
            }
        });
        jPanel1.add(vddangki, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 260, 140, -1));

        btnQuenMatKhau.setBackground(new java.awt.Color(153, 153, 255));
        btnQuenMatKhau.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnQuenMatKhau.setText("Quên mật khẩu");
        btnQuenMatKhau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuenMatKhauActionPerformed(evt);
            }
        });
        jPanel1.add(btnQuenMatKhau, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 300, 140, -1));

        jCheckBox1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jCheckBox1.setText("Nhớ mật khẩu");
        jPanel1.add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, 120, -1));

        txtMatkhau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMatkhauActionPerformed(evt);
            }
        });
        jPanel1.add(txtMatkhau, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 200, -1));

        txtDangnhap.setText("Vanduy");
        txtDangnhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDangnhapActionPerformed(evt);
            }
        });
        jPanel1.add(txtDangnhap, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 200, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 345, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void vddangkiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vddangkiActionPerformed
setVisible(false);
new dangki().setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_vddangkiActionPerformed

    private void btnQuenMatKhauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuenMatKhauActionPerformed
setVisible (false);
new quenmatkhau().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_btnQuenMatKhauActionPerformed

    private void vddangnhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vddangnhapActionPerformed
 if(txtDangnhap.getText().equals("Vanduy") && txtMatkhau.getText().equals("123")){
    
     this.dispose();
     new dangnhap().setVisible(true);
 }else{
     JOptionPane.showMessageDialog(this,"Sai tên đăng nhập hoặc mật khẩu",
             "Thông báo", JOptionPane.WARNING_MESSAGE);
 }
    }//GEN-LAST:event_vddangnhapActionPerformed

    private void txtMatkhauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMatkhauActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMatkhauActionPerformed

    private void txtDangnhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDangnhapActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDangnhapActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new dn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnQuenMatKhau;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtDangnhap;
    private javax.swing.JPasswordField txtMatkhau;
    private javax.swing.JButton vddangki;
    private javax.swing.JButton vddangnhap;
    // End of variables declaration//GEN-END:variables
}
